name: twrp prebuilts build process

on:
  push:
    branches: [ android-9.0 ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout kernel repo
        uses: actions/checkout@v3
        with:
          ref: 'android-9.0'
          token: ${{320260}}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip tar

      - name: Set up environment
        id: toolchains
        run: |
          rm -rf hk-out
          mkdir -p hk-out hk-tools/clang-twrp hk-tools/aarch64-linux-android && cd hk-tools && pwd
          sudo curl -L https://corsica.nu/gcc4.9 | tar -xz -C aarch64-linux-android
          sudo curl -L https://corsica.nu/clang-twrp | tar -xz -C clang-twrp
          toolchains=$(pwd) && cd ..
          sudo wget -O /usr/bin/mkdtimg https://corsica.nu/mkdtimg && sudo chmod +x /usr/bin/mkdtimg
          echo "clang=$toolchains/clang-twrp/bin" >> $GITHUB_ENV
          echo "gcc=$toolchains/aarch64-linux-android/bin/aarch64-linux-android-" >> $GITHUB_ENV

      - name: Checkout configs repo
        uses: actions/checkout@v3
        with:
          repository: corsicanu/dtconfigs
          token: ${{ secrets.TOKEN }}
          path: hk-out/dtconfigs

      - name: Build everything
        run: |
          jobs=16
          export ARCH=arm64
          export SUBARCH=arm64
          export ANDROID_MAJOR_VERSION=r
          export PLATFORM_VERSION=11
          export CLANG_PATH=${{ env.clang }}
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=${{ env.gcc }}
          export PATH=${CLANG_PATH}:${PATH}
          combo=(beyond0lte:beyond0 beyond1lte:beyond1 beyond2lte:beyond2 beyondx:beyondx d1:d1 d2s:d2s d2x:d2x d1xks:d1x)
          for i in ${combo[@]}; do
            variant=`echo $i | cut -d':' -f2`
            rm -rf .version
            mkdir -p hk-out/$variant
            unset LOCALVERSION
            make CC=clang ARCH=arm64 exynos9820-`echo $i | cut -d':' -f1`_defconfig
            make CC=clang ARCH=arm64 -j$jobs
            cp -r arch/arm64/boot/Image hk-out/$variant/kernel
            mkdtimg cfg_create hk-out/$variant/dtbo hk-out/dtconfigs/$variant.cfg -d arch/arm64/boot/dts/samsung
          done
          rm -rf hk-out/dtconfigs
          
      - name: Generate release file
        id: files
        run: |
          basedir=$(pwd)
          tag=$(date +'%Y%m%d%H%M%S')
          date=$(date +'%d-%m-%Y')
          cd hk-out && zip -r prebuilts.zip * && cd $basedir
          echo "zip=`find -name prebuilts.zip`" >> $GITHUB_ENV
          echo "tag=$tag" >> $GITHUB_ENV
          echo "date=$date" >> $GITHUB_ENV

      - name: Update current version and create log
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull origin ${{github.ref}} --ff-only
          git tag ${{ env.tag }}

      - name: Push changes to repo
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.TOKEN }}
          branch: ${{github.ref}}

      - name: Upload release assets
        uses: CaptainThrowback/action-gh-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: ${{ env.tag }}
          name: Prebuilts of ${{ env.date }}
          files: |
            ${{ env.zip }}
